from pathlib import Path
from typing import Optional, Literal

from pydantic import BaseModel
from pydantic_settings import BaseSettings, SettingsConfigDict

from shared import RedisConfig, BrokerConfig

BASE_DIR = Path(__file__).resolve().parent.parent.parent
ENV_PATH = BASE_DIR / ".env"


class APIDocsSettings(BaseModel):
    """Settings related with the API autogenerated documentation"""

    title: str = "Text Canvas"
    """Title of the API"""
    description: Optional[str] = None
    """Description of the API"""
    version: str = "0.1.0"
    """Version of the API"""


class StyleSettings(BaseModel):
    styles: list[str] = []  # CSS Styles


class LoggingConfig(BaseModel):
    """Settings related with the logging of requests"""

    level: Literal[
        "trace",
        "debug",
        "info",
        "success",
        "warning",
        "error",
        "critical",
    ] = "debug"
    serialize: bool = False


class DatabaseConfig(BaseModel):
    user: str
    password: str
    name: str
    host: str
    port: int
    echo: bool = False
    pool_size: int = 50
    max_overflow: int = 10
    naming_convention: dict[str, str] = {
        "ix": "ix_%(column_0_label)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s",
    }

    @property
    def url(self):
        return f"postgresql+asyncpg://{self.user}:{self.password}@{self.host}:{self.port}/{self.name}"


class RunConfig(BaseModel):
    reload: bool = True
    host: str = "0.0.0.0"
    port: int = 8000


class ApiPrefix(BaseModel):
    prefix: str = "/api"
    tasks: str = "/tasks"


class TasksSettings(BaseModel):
    """Settings for tasks processing"""

    # Maximum input data size in bytes (64 KB by default)
    max_input_size: int = 1024 * 64


class AuthJWTConfig(BaseModel):
    private_key_path: Path = BASE_DIR / "src" / "certs" / "jwt-private.pem"
    public_key_path: Path = BASE_DIR / "src" / "certs" / "jwt-public.pem"
    algorithm: str = "RS256"
    refresh_token_expire_days: int = 30
    access_token_expire_minutes: int = 15
    token_type_field: str = "type"
    access_token_field: str = "access"
    refresh_token_field: str = "refresh"
    refresh_token_cookie_max_age: int = 30 * 24 * 60 * 60


class EmailSettings(BaseModel):
    """Settings for sending emails and verification links"""

    smtp_host: str = "localhost"
    smtp_port: int = 1025
    default_from: str = "textcanvas@mail.ru"
    # Base URL used to form verification links, without the token query param
    verification_base_url: str = "http://0.0.0.0:8000/api/v1/auth/verify"
    # Token lifetime for email verification in minutes
    verification_token_expire_minutes: int = 15
    smtp_user: str
    smtp_password: str
    smtp_start_tls: bool = False
    smtp_use_tls: bool = False


class Settings(BaseSettings):
    docs: APIDocsSettings = APIDocsSettings()
    logging: LoggingConfig = LoggingConfig()
    db: DatabaseConfig
    run: RunConfig = RunConfig()
    api: ApiPrefix = ApiPrefix()
    auth: AuthJWTConfig = AuthJWTConfig()
    style: StyleSettings = StyleSettings()
    email: EmailSettings
    tasks: TasksSettings = TasksSettings()
    rmq: BrokerConfig
    redis: RedisConfig
    model_config = SettingsConfigDict(
        env_file=ENV_PATH,
        extra="ignore",
        case_sensitive=False,
        env_nested_delimiter="__",
    )


settings = Settings()
